[package]
name = "carlos"
version = "0.1.0"
description = "Car Layers Open Source ... or something like that"
authors = ["Daniel Olano <danielolanoc@gmail.com>"]
edition = "2018"

[dependencies]
capnp = "*"
# failure = "0.1"

[build-dependencies]
capnpc = "0.9"
