[package]
name = "carlos"
version = "0.1.0"
authors = ["Daniel Olano <danielolanoc@gmail.com>"]
edition = "2018"

[dependencies]
gstreamer = "0.13.0"
#glib = "0.7.1"
failure = "0.1.5"

[build-dependencies]
capnpc = "0.9"
